"""Strategy encoding and evaluation."""

from tsd.strategy.evaluator import (
    BacktestMetrics,
    BacktestResult,
    EvaluatorConfig,
    TradeRecord,
    run_backtest,
)
from tsd.strategy.execution import (
    ENTRY_TIMING,
    EXIT_TIMING_INDICATOR,
    EXIT_TIMING_LIMIT,
    EXIT_TIMING_TIME,
    check_limit_exit,
    shift_to_next_open,
)
from tsd.strategy.exits import (
    compute_breakeven_level,
    compute_chandelier_levels,
    compute_stop_loss_level,
    compute_take_profit_level,
    compute_trailing_stop_levels,
    generate_indicator_exit_signals,
    generate_time_exit_signal,
)
from tsd.strategy.genome import (
    BreakevenConfig,
    ChandelierConfig,
    FilterGene,
    IndicatorExitGene,
    IndicatorGene,
    LimitExitGene,
    OutputMeta,
    StopLossConfig,
    StrategyGenome,
    StrategyMeta,
    TakeProfitConfig,
    TimeExitGene,
    TrailingStopConfig,
    flat_to_genome,
    genome_length,
    genome_to_flat,
    load_strategy_config,
    random_genome,
    validate_genome,
)
from tsd.strategy.signals import apply_condition, generate_entry_signals

__all__ = [
    "BacktestMetrics",
    "BacktestResult",
    "ENTRY_TIMING",
    "EvaluatorConfig",
    "EXIT_TIMING_INDICATOR",
    "EXIT_TIMING_LIMIT",
    "EXIT_TIMING_TIME",
    "BreakevenConfig",
    "ChandelierConfig",
    "FilterGene",
    "IndicatorExitGene",
    "IndicatorGene",
    "LimitExitGene",
    "OutputMeta",
    "StopLossConfig",
    "StrategyGenome",
    "StrategyMeta",
    "TakeProfitConfig",
    "TimeExitGene",
    "TradeRecord",
    "TrailingStopConfig",
    "apply_condition",
    "check_limit_exit",
    "compute_breakeven_level",
    "compute_chandelier_levels",
    "compute_stop_loss_level",
    "compute_take_profit_level",
    "compute_trailing_stop_levels",
    "flat_to_genome",
    "generate_entry_signals",
    "generate_indicator_exit_signals",
    "generate_time_exit_signal",
    "genome_length",
    "genome_to_flat",
    "load_strategy_config",
    "random_genome",
    "run_backtest",
    "shift_to_next_open",
    "validate_genome",
]
